/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.proyect.Vistas.VentanasPrincipales;

import org.proyect.Vistas.Ventana;

/**
 *
 * @author manue
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame implements Ventana {

    /**
     * Creates new form VentanaMenuPrincipal
     */
    @Override
    public void iniciar() {
        this.setVisible(true);
        this.setTitle("Registrar Asistencia");
    }

    @Override
    public void cerrar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public VentanaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonRegistrarAsistencia = new javax.swing.JButton();
        jButtonRegistrarEmpleado = new javax.swing.JButton();
        jButtonBuscarAsistencia = new javax.swing.JButton();
        jButtonBuscarEmpleado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 62, 89));
        jLabel1.setText("Menú Principal");
        jLabel1.setPreferredSize(new java.awt.Dimension(524, 62));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 320, -1));

        jButtonCerrarSesion.setBackground(new java.awt.Color(231, 73, 73));
        jButtonCerrarSesion.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jButtonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 160, 40));

        jButtonRegistrarAsistencia.setBackground(new java.awt.Color(57, 62, 89));
        jButtonRegistrarAsistencia.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 22)); // NOI18N
        jButtonRegistrarAsistencia.setForeground(new java.awt.Color(111, 191, 191));
        jButtonRegistrarAsistencia.setText("Registrar Asistencia");
        jButtonRegistrarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 150, 250, 60));

        jButtonRegistrarEmpleado.setBackground(new java.awt.Color(57, 62, 89));
        jButtonRegistrarEmpleado.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jButtonRegistrarEmpleado.setForeground(new java.awt.Color(111, 191, 191));
        jButtonRegistrarEmpleado.setText("Registrar Empleado");
        jButtonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 178, 40));

        jButtonBuscarAsistencia.setBackground(new java.awt.Color(111, 191, 191));
        jButtonBuscarAsistencia.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jButtonBuscarAsistencia.setForeground(new java.awt.Color(57, 62, 89));
        jButtonBuscarAsistencia.setText("Buscar Asistencia");
        jButtonBuscarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 160, 40));

        jButtonBuscarEmpleado.setBackground(new java.awt.Color(111, 191, 191));
        jButtonBuscarEmpleado.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jButtonBuscarEmpleado.setForeground(new java.awt.Color(57, 62, 89));
        jButtonBuscarEmpleado.setText("Buscar Empleado");
        jButtonBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 160, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("@Todos los derechos reservados grupo 3");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonRegistrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarAsistenciaActionPerformed

    private void jButtonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarEmpleadoActionPerformed

    private void jButtonBuscarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarAsistenciaActionPerformed

    private void jButtonBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBuscarAsistencia;
    public javax.swing.JButton jButtonBuscarEmpleado;
    public javax.swing.JButton jButtonCerrarSesion;
    public javax.swing.JButton jButtonRegistrarAsistencia;
    public javax.swing.JButton jButtonRegistrarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
